name: simple_invoice_system
version: 1.0.0+1
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  firebase_storage: ^11.0.5
  pdf: ^3.8.4
  printing: ^5.9.3
  modal_progress_hud_nsn: ^0.3.0
  file_picker: ^5.2.2


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

